code --install-extension 2gua.rainbow-brackets
code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.jenkins-status
code --install-extension Angular.ng-template
code --install-extension anseki.vscode-color
code --install-extension ashinzekene.nestjs
code --install-extension be5invis.vscode-custom-css
code --install-extension bibhasdn.unique-lines
code --install-extension bmalehorn.vscode-fish
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-multiple-files
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.github-actions
code --install-extension glen-84.sass-lint
code --install-extension Gruntfuggly.todo-tree
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hbenl.vscode-jasmine-test-adapter
code --install-extension hbenl.vscode-test-explorer
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension ivory-lab.jenkinsfile-support
code --install-extension janjoerke.jenkins-pipeline-linter-connector
code --install-extension jkjustjoshing.vscode-text-pastry
code --install-extension joelday.docthis
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension KnisterPeter.vscode-github
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension lunaryorn.fish-ide
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-apache
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension natewallace.angular2-inline
code --install-extension norato.storybook-snippets
code --install-extension nrwl.angular-console
code --install-extension pflannery.vscode-versionlens
code --install-extension pnp.polacode
code --install-extension Prisma.vscode-graphql
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension ryu1kn.partial-diff
code --install-extension secanis.jenkinsfile-support
code --install-extension shakram02.bash-beautify
code --install-extension Shan.code-settings-sync
code --install-extension shanoor.vscode-nginx
code --install-extension skyapps.fish-vscode
code --install-extension SonarSource.sonarlint-vscode
code --install-extension syler.sass-indented
code --install-extension techer.open-in-browser
code --install-extension Tyriar.lorem-ipsum
code --install-extension Tyriar.sort-lines
code --install-extension vector-of-bool.gitflow
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WallabyJs.quokka-vscode
code --install-extension WallabyJs.wallaby-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wesbos.theme-cobalt2
code --install-extension william-voyek.vscode-nginx
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JasmineSnippets
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Yummygum.city-lights-icon-vsc
